"""empty message

Revision ID: 5ff0808166b5
Revises: 480e2bc420d9
Create Date: 2022-08-16 12:22:59.125010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff0808166b5'
down_revision = '480e2bc420d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seekeing_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seekeing_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
